language: ruby
rvm:
 - 2.3.0
 #- jruby
 #- rbx-2
services:
  - postgresql

before_script:
  - psql -c 'create database tourpal_test;' -U postgres
# uncomment and edit the following line if your project needs to run something other than `rake`:
script: bundle exec rspec ./spec
